// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://2k3vag5kang55ebcza7ilsgzlm.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "us-east-2:8b9db0da-ba6d-4603-8895-c32f666556e2",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_70BZTMByD",
    "aws_user_pools_web_client_id": "2o0qug170d06ggph6c8m6hrsn7"
};


export default awsmobile;
